# use zsh by default
set -g default-shell /bin/zsh 

set -g default-terminal "screen-256color" # enable 256-color support
set -ga terminal-overrides ",*256col*:Tc" # enable true-color for compatible terminals
#set -ga terminal-overrides ",alacritty:Tc" 
set -ga terminal-features "*:hyperlinks"

set-option -g history-limit 1000000

set -g set-clipboard on
set -g mouse on
set -g set-titles on
set -g set-titles-string "#T"
set -g detach-on-destroy off
set -g allow-passthrough on
set -g status-position bottom

set-option -g focus-events on

# refresh tmux config with 'r'
unbind r
bind r source-file ~/.tmux.conf

# resize panes
bind-key -r -T prefix M-Up resize-pane -U 5
bind-key -r -T prefix M-Down resize-pane -D 5
bind-key -r -T prefix M-Left resize-pane -L 5
bind-key -r -T prefix M-Right resize-pane -R 5

# with vim keys
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# move between panes with vim keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enable vi mode to allow us to use vim keys to move around in copy mode (Prefix + [ places us in copy mode)
set-window-option -g mode-keys vi

# Start selecting text with "v"
bind-key -T copy-mode-vi 'v' send -X begin-selection 

# Copy text with "y"
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "pbcopy"

# Paste yanked text with "Prefix + P" ("Prefix + p" goes to previous window)
bind P paste-buffer

# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane


# tpm plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# List of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # Enable navigating between nvim and tmux


source-file ~/.config/tmux/base16-gruvbox-dark-pale.conf


# ensure that the repo is cloned first
# ❯ pwd
# /home/pimeson/.config/tmux
# git clone https://github.com/tmux-plugins/tpm plugins/tpm 

run '~/.config/tmux/plugins/tpm/tpm'


